/*
 * JMeuMeuGameField.java
 *
 * Created on 6 mai 2008, 17:48
 */

package jmeumeu;

import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author  Jeremy
 */
public class JMeuMeuGameField extends javax.swing.JFrame {

    /** Creates new form JMeuMeuGameField */
    public JMeuMeuGameField(JMeuMeuView View) {
        initComponents();
        _View = View;
      
        this.jLabel4.setText(Integer.toString(_View._Datas.ecus));
        
        getFrames()[1].setTitle("Projet JMeuMeu");
        
        _Welcome = new GameField.Welcome(View);
        _Welcome.setSize(this.jPanel2.getSize().width, this.jPanel2.getSize().height);
        
        _Poulailler = new GameField.Poulailler(View, this);
        _Poulailler.setSize(this.jPanel2.getSize().width, this.jPanel2.getSize().height);
        
        _Clapier = new GameField.Clapier(View, this);
        _Clapier.setSize(this.jPanel2.getSize().width, this.jPanel2.getSize().height);
        
        _Paturage = new GameField.Paturage(View, this);
        _Paturage.setSize(this.jPanel2.getSize().width, this.jPanel2.getSize().height);
        
        _Remise = new GameField.Remise(View);
        _Remise.setSize(this.jPanel2.getSize().width, this.jPanel2.getSize().height);
        
        _Cooperative = new GameField.Cooperative(View);
        _Cooperative.setSize(this.jPanel2.getSize().width, this.jPanel2.getSize().height);
        
        _Marche = new GameField.Marche(View);
        _Marche.setSize(this.jPanel2.getSize().width, this.jPanel2.getSize().height);
        
        jPanel2.add(_Welcome);
        jPanel2.add(_Poulailler);
        jPanel2.add(_Clapier);
        jPanel2.add(_Paturage);
        jPanel2.add(_Remise);
        jPanel2.add(_Cooperative);
        jPanel2.add(_Marche);
        
        ((GameField.Welcome)jPanel2.getComponent(0)).Show();
        ((GameField.Poulailler)jPanel2.getComponent(1)).Hide();
        ((GameField.Clapier)jPanel2.getComponent(2)).Hide();
        ((GameField.Paturage)jPanel2.getComponent(3)).Hide();
        ((GameField.Remise)jPanel2.getComponent(4)).Hide();
        ((GameField.Cooperative)jPanel2.getComponent(5)).Hide();
        ((GameField.Marche)jPanel2.getComponent(6)).Hide();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(jmeumeu.JMeuMeuApp.class).getContext().getResourceMap(JMeuMeuGameField.class);
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setToolTipText(resourceMap.getString("jButton1.toolTipText")); // NOI18N
        jButton1.setActionCommand(resourceMap.getString("jButton1.actionCommand")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setToolTipText(resourceMap.getString("jButton2.toolTipText")); // NOI18N
        jButton2.setActionCommand(resourceMap.getString("jButton2.actionCommand")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });

        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setToolTipText(resourceMap.getString("jButton3.toolTipText")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });

        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setToolTipText(resourceMap.getString("jButton4.toolTipText")); // NOI18N
        jButton4.setName("jButton4"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });

        jButton5.setText(resourceMap.getString("jButton5.text")); // NOI18N
        jButton5.setToolTipText(resourceMap.getString("jButton5.toolTipText")); // NOI18N
        jButton5.setName("jButton5"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setFont(resourceMap.getFont("lblEcus.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("lblEcus.text")); // NOI18N
        jLabel3.setName("lblEcus"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setFont(resourceMap.getFont("lblPoints.font")); // NOI18N
        jLabel5.setText(resourceMap.getString("lblPoints.text")); // NOI18N
        jLabel5.setName("lblPoints"); // NOI18N

        jLabel6.setText(resourceMap.getString("lblNumPoints.text")); // NOI18N
        jLabel6.setName("lblNumPoints"); // NOI18N

        jLabel7.setFont(resourceMap.getFont("lblRank.font")); // NOI18N
        jLabel7.setText(resourceMap.getString("lblRank.text")); // NOI18N
        jLabel7.setName("lblRank"); // NOI18N

        jLabel8.setText(resourceMap.getString("lblNumRank.text")); // NOI18N
        jLabel8.setName("lblNumRank"); // NOI18N

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        jButton6.setText(resourceMap.getString("jButton6.text")); // NOI18N
        jButton6.setActionCommand(resourceMap.getString("jButton6.actionCommand")); // NOI18N
        jButton6.setName("jButton6"); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });

        jButton7.setText(resourceMap.getString("jButton7.text")); // NOI18N
        jButton7.setActionCommand(resourceMap.getString("jButton7.actionCommand")); // NOI18N
        jButton7.setName("jButton7"); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });

        jButton8.setText(resourceMap.getString("jButton8.text")); // NOI18N
        jButton8.setToolTipText(resourceMap.getString("jButton8.toolTipText")); // NOI18N
        jButton8.setActionCommand(resourceMap.getString("jButton8.actionCommand")); // NOI18N
        jButton8.setName("jButton8"); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });
        
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, 300)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(238, Short.MAX_VALUE))
        );

        jLabel3.getAccessibleContext().setAccessibleName(resourceMap.getString("jLabel3.AccessibleContext.accessibleName")); // NOI18N
        jLabel4.getAccessibleContext().setAccessibleName(resourceMap.getString("jLabel4.AccessibleContext.accessibleName")); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActionPerformed
    
    String s = evt.getActionCommand();
    
    if(s.equals("Deconnexion"))
    {
        if(JMeuMeuHelpers.ShowQuestionMessage("Voulez-vous vraiment vous déconnecter ?")  == 0)
        {
/*           if(_View._Oracle.Deconnexion())
            {*/
                this.setVisible(false);
                _View.show();
           /* }
           else
               JMeuMeuHelpers.ShowDeconnexionError();*/
        }
    }
    else if(s.equals("Poulailler"))
    {
        ((GameField.Welcome)jPanel2.getComponent(0)).Hide();
        ((GameField.Poulailler)jPanel2.getComponent(1)).Show();
        ((GameField.Clapier)jPanel2.getComponent(2)).Hide();
        ((GameField.Paturage)jPanel2.getComponent(3)).Hide();
        ((GameField.Remise)jPanel2.getComponent(4)).Hide();
        ((GameField.Cooperative)jPanel2.getComponent(5)).Hide();
        ((GameField.Marche)jPanel2.getComponent(6)).Hide();
    }
    else if(s.equals("Clapier"))
    {
        ((GameField.Welcome)jPanel2.getComponent(0)).Hide();
        ((GameField.Poulailler)jPanel2.getComponent(1)).Hide();
        ((GameField.Clapier)jPanel2.getComponent(2)).Show();
        ((GameField.Paturage)jPanel2.getComponent(3)).Hide();
        ((GameField.Remise)jPanel2.getComponent(4)).Hide();
        ((GameField.Cooperative)jPanel2.getComponent(5)).Hide();
        ((GameField.Marche)jPanel2.getComponent(6)).Hide();
    }
    else if(s.equals("Paturage"))
    {
        ((GameField.Welcome)jPanel2.getComponent(0)).Hide();
        ((GameField.Poulailler)jPanel2.getComponent(1)).Hide();
        ((GameField.Clapier)jPanel2.getComponent(2)).Hide();
        ((GameField.Paturage)jPanel2.getComponent(3)).Show();
        ((GameField.Remise)jPanel2.getComponent(4)).Hide();
        ((GameField.Cooperative)jPanel2.getComponent(5)).Hide();
        ((GameField.Marche)jPanel2.getComponent(6)).Hide();
    }
    else if(s.equals("Remise"))
    {
        ((GameField.Welcome)jPanel2.getComponent(0)).Hide();
        ((GameField.Poulailler)jPanel2.getComponent(1)).Hide();
        ((GameField.Clapier)jPanel2.getComponent(2)).Hide();
        ((GameField.Paturage)jPanel2.getComponent(3)).Hide();
        ((GameField.Remise)jPanel2.getComponent(4)).Show();
        ((GameField.Cooperative)jPanel2.getComponent(5)).Hide();
        ((GameField.Marche)jPanel2.getComponent(6)).Hide();
    }
    else if(s.equals("Cooperative"))
    {
        ((GameField.Welcome)jPanel2.getComponent(0)).Hide();
        ((GameField.Poulailler)jPanel2.getComponent(1)).Hide();
        ((GameField.Clapier)jPanel2.getComponent(2)).Hide();
        ((GameField.Paturage)jPanel2.getComponent(3)).Hide();
        ((GameField.Remise)jPanel2.getComponent(4)).Hide();
        ((GameField.Cooperative)jPanel2.getComponent(5)).Show();
        ((GameField.Marche)jPanel2.getComponent(6)).Hide();
    }
    else if(s.equals("Marche"))
    {
        ((GameField.Welcome)jPanel2.getComponent(0)).Hide();
        ((GameField.Poulailler)jPanel2.getComponent(1)).Hide();
        ((GameField.Clapier)jPanel2.getComponent(2)).Hide();
        ((GameField.Paturage)jPanel2.getComponent(3)).Hide();
        ((GameField.Remise)jPanel2.getComponent(4)).Hide();
        ((GameField.Cooperative)jPanel2.getComponent(5)).Hide();
        ((GameField.Marche)jPanel2.getComponent(6)).Show();
    }
    else if(s.equals("Hibernation"))
    {
        
        if(JMeuMeuHelpers.ShowQuestionMessage("Voulez-vous vraiment passer en hibernation ?")  == 0)
        {
            if(_View._Oracle.Deconnexion())
            {
                this.setVisible(false);
                _View.show();
            }
        }
    }
}//GEN-LAST:event_ButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JMeuMeuGameField(null).setVisible(true);
            }
        });
    }
    
    private int GetEcus()
    {
        ResultSet RS = _View._Oracle.Query("SELECT ECUS FROM FERME");
        
        int ecus = 0;
        
        try
        {
            ecus = RS.getInt(1);
        }
        catch(SQLException e)
        {
            JMeuMeuHelpers.ShowErrorMessage(e.getMessage());
            return 0;
        }
        
        return ecus;
    }
    
    public void SetEcus()
    {
    	this.jLabel4.setText(Integer.toString(_View._Datas.ecus));
    }
    
    private String IsCowExist()
    {
        ResultSet RS = _View._Oracle.Query("SELECT ABREUVAGE_VACHE FROM FERME");
        
        String x = null;
        
        try
        {
            x = RS.getString(1);
        }
        catch(SQLException e)
        {
            JMeuMeuHelpers.ShowErrorMessage(e.getMessage());
            return null;
        }
        
        return x;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
 
    // End of variables declaration//GEN-END:variables

    private JMeuMeuView _View;
    
    private GameField.Welcome        _Welcome;
    private GameField.Poulailler     _Poulailler;
    private GameField.Clapier        _Clapier;
    private GameField.Paturage       _Paturage;
    private GameField.Remise         _Remise;
    private GameField.Cooperative    _Cooperative;
    private GameField.Marche         _Marche;
}
