/*
 * JMeuMeuMenuCreerCompteView.java
 *
 * Created on 6 mai 2008, 11:46
 */

package jmeumeu;


/**
 *
 * @author  Jeremy
 */
public class JMeuMeuMenuCreerCompteView extends javax.swing.JFrame {

    /** Creates new form JMeuMeuMenuCreerCompteView */
    public JMeuMeuMenuCreerCompteView(JMeuMeuView View) {
        initComponents();
        this.setTitle("Création d'un compte");

        _View = View;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
     // <editor-fold defaultstate="collapsed" desc="Generated Code">    
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(jmeumeu.JMeuMeuApp.class).getContext().getResourceMap(JMeuMeuMenuCreerCompteView.class);
        jLabel1.setFont(resourceMap.getFont("lblCreateCompte.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("lblCreateCompte.text")); // NOI18N
        jLabel1.setName("lblCreateCompte"); // NOI18N

        jLabel2.setText(resourceMap.getString("lblID.text")); // NOI18N
        jLabel2.setName("lblID"); // NOI18N

        jLabel3.setText(resourceMap.getString("lblUserName.text")); // NOI18N
        jLabel3.setName("lblUserName"); // NOI18N

        jLabel4.setText(resourceMap.getString("lblPwd.text")); // NOI18N
        jLabel4.setName("lblPwd"); // NOI18N

        jLabel5.setText(resourceMap.getString("lblVerifPwd.text")); // NOI18N
        jLabel5.setName("lblVerifPwd"); // NOI18N

        jLabel6.setText(resourceMap.getString("lblEmail.text")); // NOI18N
        jLabel6.setName("lblEmail"); // NOI18N

        jButton1.setText(resourceMap.getString("btnCreerCompte.text")); // NOI18N
        jButton1.setActionCommand(resourceMap.getString("btnCreerCompte.actionCommand")); // NOI18N
        jButton1.setName("btnCreerCompte"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });

        jButton2.setText(resourceMap.getString("btnCancel.text")); // NOI18N
        jButton2.setName("btnCancel"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });

        jTextField1.setText(resourceMap.getString("txtIdentifiant.text")); // NOI18N
        jTextField1.setName("txtIdentifiant"); // NOI18N

        jTextField2.setText(resourceMap.getString("txtUserName.text")); // NOI18N
        jTextField2.setName("txtUserName"); // NOI18N

        jTextField5.setText(resourceMap.getString("txtMail.text")); // NOI18N
        jTextField5.setName("txtMail"); // NOI18N

        jPasswordField1.setText(resourceMap.getString("txtPassword.text")); // NOI18N
        jPasswordField1.setName("txtPassword"); // NOI18N

        jPasswordField2.setText(resourceMap.getString("txtChkPwd.text")); // NOI18N
        jPasswordField2.setName("txtChkPwd"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(93, 93, 93)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(39, 39, 39)
                                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        this.setSize(100, 100);
        pack();
    }// </editor-fold>   
    
private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActionPerformed

    String Action = evt.getActionCommand();
    
    if(Action.equals("Annuler"))
    {
        this.dispose();
        JMeuMeuApp.getApplication().show(_View);
    }
    else if(Action.equals("CC"))
    {
        if(CheckValues())
        {
            if(_View._Oracle.Connexion())
            {
                if(_View._Oracle.callProc("Creation_Compte", getID()+"', '"+getUserName()+"','"+getPassword()+"','"+getEmail()))
                {
                	JMeuMeuHelpers.ShowInformationMessage("Compte Crée avec Succès");
                }
            }
        }
    }
}//GEN-LAST:event_ButtonActionPerformed

    private boolean CheckValues()
    {
        String Pass1 = "";
        String Pass2 = "";
        
        Pass1 = JMeuMeuHelpers.ToString(jPasswordField1.getPassword());
        Pass2 = JMeuMeuHelpers.ToString(jPasswordField2.getPassword());
     
        if(!Pass1.equals(Pass2))
        {
            JMeuMeuHelpers.ShowErrorMessage(JMeuMeuMessages.WrongPassWords);
            
            return false;
        }
        
        if(!JMeuMeuHelpers.IsEmailAddress(this.jTextField5.getText()))
        {
            JMeuMeuHelpers.ShowErrorMessage(JMeuMeuMessages.WrongEmailFormat);
            
            return false;
        }
        
        return true;
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JMeuMeuMenuCreerCompteView(null).setVisible(true);
            }
        });
    }
    
    public String getID()
    {
        return this.jTextField1.getText();
    }
    
    public String getUserName()
    {
        return this.jTextField2.getText();
    }
    
    public String getEmail()
    {
        return this.jTextField5.getText();
    }
    
    public String getPassword()
    {
        return JMeuMeuHelpers.ToString(this.jPasswordField1.getPassword());
    }

    private JMeuMeuView _View;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

}
